### ISSUE TITLE
now --ffast-math doesn't mess with FTZ/DOZ. Time to edit or make new article?

### ISSUE THREAD

**Issue by NHOrus** [trofi/trofi.github.io.gen#16]
now with bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55522 closed and shared libraries not tainting stuff with subnormals, is it time to make amends for existing article or make a new one, expanding on current situation?

**Comment by trofi** [comment]
Updating sounds fine. Would updating `Tl;DR` wording to mention compiler version for library case be enough? Or you see more places in need to update?

The initial article contained this verbiage in the middle:

"""
This effect was seen as too problematic by many and gcc-13 stopped enabling crtfastmath.o for libraries (-shared option) in https://gcc.gnu.org/PR55522.

While the fix limits the impact to final programs that enable -Ofast it is still able to break all the libraries linked into the program linked with -Ofast.

As the library test suites are usually not ran with -Ofast the breakage might not be noticed until data corruption starts happening on real data in final applications.
"""

**Comment by NHOrus** [comment]
Ah, I missed this verbage. I think mentioning compiler version in TL;DR sounds fine.
And the're a Clang bug that follows along and stops enabling crtfastmath.o for libraries, too. 
https://github.com/llvm/llvm-project/issues/57589
It's not yet in any Clang releases, I think? But should be in Clang-19. Hopefully. I don't know.

**Comment by trofi** [comment]
- updated `TL;DR` as https://github.com/trofi/trofi.github.io.gen/commit/8d2da04f205f1735396fbdb6c533ecb4a859b477
- mentioned upcoming `clang-19` change and `-mdaz-ftz` / `-mno-daz-ftz` clags as https://github.com/trofi/trofi.github.io.gen/commit/3c72844c44a321ed3bab8b4f6aa504392b4f18b1

**Comment by trofi** [comment]
I assume the above is enough. Declaring it done.
