### ISSUE TITLE
246-dropping-disqus-comments.html errata

### ISSUE THREAD

**Issue by MaskRay** [trofi/trofi.github.io.gen#3]
> as a custom version thighs would

`thighs` => typo?

> -isystem, -idirafter, -isysroot, -Iquote

s/-Iquote/-iquote/

> { LANG=C gcc hello.o -o hello -Wl,--verbose -L/tmp/custom-glibc-install/lib | fgrep succeeded; } |& unnix

s/--verbose/-t/ => the output will be conciser.

> They explicitly disable search paths for: include paths, startup files or standard and runtime support libraries.

"search paths" implies that the disabled objects are search paths but all except `-nostdinc` deal with files.

**Comment by trofi** [comment]
All good points. Thank you!

> s/--verbose/-t/ => the output will be conciser.

TIL! Proposed changes as: https://github.com/trofi/trofi.github.io.gen/pull/4 . WDYT?
